# Cloudeep Official .prettierrc.yaml
printWidth: 180
useTabs: true
tabWidth: 4
overrides:
  - files: "*.js"
    options:
      editor.formatOnSave: true
      singleQuote: true
      semi: true
      printWidth: 120
      trailingComma: es5
      arrowParens: avoid
